package com.lh.foodRecommend.dao;

import com.lh.food.entity.Food;
import com.lh.foodRecommend.entity.FoodRecommend;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FoodRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodrecommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodrecommend
     *
     * @mbg.generated
     */
    int insert(FoodRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodrecommend
     *
     * @mbg.generated
     */
    FoodRecommend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodrecommend
     *
     * @mbg.generated
     */
    List<FoodRecommend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodrecommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FoodRecommend record);

    Food selectFoodByReId(String frId);

    List<Food> selectFoodReAll();
}