package com.lh.foodclass.dao;

import com.lh.foodclass.entity.Foodclass;
import java.util.List;

public interface FoodclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodclass
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodclass
     *
     * @mbg.generated
     */
    int insert(Foodclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodclass
     *
     * @mbg.generated
     */
    Foodclass selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodclass
     *
     * @mbg.generated
     */
    List<Foodclass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodclass
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Foodclass record);
}