package com.lh.foodRecommend.entity;

import java.io.Serializable;

public class FoodRecommend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodrecommend.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodrecommend.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodrecommend.fk_food_id
     *
     * @mbg.generated
     */
    private String fkFoodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodrecommend.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodrecommend.isShow
     *
     * @mbg.generated
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foodrecommend
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodrecommend.id
     *
     * @return the value of foodrecommend.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodrecommend.id
     *
     * @param id the value for foodrecommend.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodrecommend.photo
     *
     * @return the value of foodrecommend.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodrecommend.photo
     *
     * @param photo the value for foodrecommend.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodrecommend.fk_food_id
     *
     * @return the value of foodrecommend.fk_food_id
     *
     * @mbg.generated
     */
    public String getFkFoodId() {
        return fkFoodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodrecommend.fk_food_id
     *
     * @param fkFoodId the value for foodrecommend.fk_food_id
     *
     * @mbg.generated
     */
    public void setFkFoodId(String fkFoodId) {
        this.fkFoodId = fkFoodId == null ? null : fkFoodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodrecommend.note
     *
     * @return the value of foodrecommend.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodrecommend.note
     *
     * @param note the value for foodrecommend.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodrecommend.isShow
     *
     * @return the value of foodrecommend.isShow
     *
     * @mbg.generated
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodrecommend.isShow
     *
     * @param isshow the value for foodrecommend.isShow
     *
     * @mbg.generated
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodrecommend
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", photo=").append(photo);
        sb.append(", fkFoodId=").append(fkFoodId);
        sb.append(", note=").append(note);
        sb.append(", isshow=").append(isshow);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}