package com.lh.foodstep.dao;

import com.lh.foodstep.entity.Foodstep;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FoodstepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstep
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstep
     *
     * @mbg.generated
     */
    int insert(Foodstep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstep
     *
     * @mbg.generated
     */
    Foodstep selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstep
     *
     * @mbg.generated
     */
    List<Foodstep> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstep
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Foodstep record);

    List<Foodstep> selectByFoodId(String foodId);
}