package com.lh.foodstep.entity;

import java.io.Serializable;

public class Foodstep implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstep.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstep.index
     *
     * @mbg.generated
     */
    private Integer index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstep.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstep.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstep.fk_food_id
     *
     * @mbg.generated
     */
    private String fkFoodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foodstep
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstep.id
     *
     * @return the value of foodstep.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstep.id
     *
     * @param id the value for foodstep.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstep.index
     *
     * @return the value of foodstep.index
     *
     * @mbg.generated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstep.index
     *
     * @param index the value for foodstep.index
     *
     * @mbg.generated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstep.info
     *
     * @return the value of foodstep.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstep.info
     *
     * @param info the value for foodstep.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstep.link
     *
     * @return the value of foodstep.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstep.link
     *
     * @param link the value for foodstep.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstep.fk_food_id
     *
     * @return the value of foodstep.fk_food_id
     *
     * @mbg.generated
     */
    public String getFkFoodId() {
        return fkFoodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstep.fk_food_id
     *
     * @param fkFoodId the value for foodstep.fk_food_id
     *
     * @mbg.generated
     */
    public void setFkFoodId(String fkFoodId) {
        this.fkFoodId = fkFoodId == null ? null : fkFoodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstep
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", index=").append(index);
        sb.append(", info=").append(info);
        sb.append(", link=").append(link);
        sb.append(", fkFoodId=").append(fkFoodId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}