package com.lh.hotfood.dao;

import com.lh.food.entity.Food;
import com.lh.hotfood.entity.Hotfood;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface HotfoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotfood
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotfood
     *
     * @mbg.generated
     */
    int insert(Hotfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotfood
     *
     * @mbg.generated
     */
    Hotfood selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotfood
     *
     * @mbg.generated
     */
    List<Hotfood> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotfood
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hotfood record);

    List<Food> selectHotFood();
}