package com.lh.food.entity;

import java.io.Serializable;

public class Food implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.ingredients
     *
     * @mbg.generated
     */
    private String ingredients;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.burden
     *
     * @mbg.generated
     */
    private String burden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.tags
     *
     * @mbg.generated
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.imtro
     *
     * @mbg.generated
     */
    private String imtro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table food
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.id
     *
     * @return the value of food.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.id
     *
     * @param id the value for food.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.name
     *
     * @return the value of food.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.name
     *
     * @param name the value for food.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.photo
     *
     * @return the value of food.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.photo
     *
     * @param photo the value for food.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.ingredients
     *
     * @return the value of food.ingredients
     *
     * @mbg.generated
     */
    public String getIngredients() {
        return ingredients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.ingredients
     *
     * @param ingredients the value for food.ingredients
     *
     * @mbg.generated
     */
    public void setIngredients(String ingredients) {
        this.ingredients = ingredients == null ? null : ingredients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.burden
     *
     * @return the value of food.burden
     *
     * @mbg.generated
     */
    public String getBurden() {
        return burden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.burden
     *
     * @param burden the value for food.burden
     *
     * @mbg.generated
     */
    public void setBurden(String burden) {
        this.burden = burden == null ? null : burden.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.info
     *
     * @return the value of food.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.info
     *
     * @param info the value for food.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.note
     *
     * @return the value of food.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.note
     *
     * @param note the value for food.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.tags
     *
     * @return the value of food.tags
     *
     * @mbg.generated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.tags
     *
     * @param tags the value for food.tags
     *
     * @mbg.generated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.imtro
     *
     * @return the value of food.imtro
     *
     * @mbg.generated
     */
    public String getImtro() {
        return imtro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.imtro
     *
     * @param imtro the value for food.imtro
     *
     * @mbg.generated
     */
    public void setImtro(String imtro) {
        this.imtro = imtro == null ? null : imtro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", photo=").append(photo);
        sb.append(", ingredients=").append(ingredients);
        sb.append(", burden=").append(burden);
        sb.append(", info=").append(info);
        sb.append(", note=").append(note);
        sb.append(", tags=").append(tags);
        sb.append(", imtro=").append(imtro);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}