package com.lh.userCollection.dao;

import com.lh.food.entity.Food;
import com.lh.userCollection.entity.UserCollection;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbg.generated
     */
    int insert(UserCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbg.generated
     */
    UserCollection selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbg.generated
     */
    List<UserCollection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserCollection record);

    UserCollection selectByUserIdAndFoodId(String userId,String foodId);

    List<Food> selectByUserId(String userId);
}