package com.lh.foodAndfoodclass.entity;

import java.io.Serializable;

public class FoodFoodclass implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_foodclass.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_foodclass.fk_food_id
     *
     * @mbg.generated
     */
    private String fkFoodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_foodclass.fk_foodclass_id
     *
     * @mbg.generated
     */
    private String fkFoodclassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table food_foodclass
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_foodclass.id
     *
     * @return the value of food_foodclass.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_foodclass.id
     *
     * @param id the value for food_foodclass.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_foodclass.fk_food_id
     *
     * @return the value of food_foodclass.fk_food_id
     *
     * @mbg.generated
     */
    public String getFkFoodId() {
        return fkFoodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_foodclass.fk_food_id
     *
     * @param fkFoodId the value for food_foodclass.fk_food_id
     *
     * @mbg.generated
     */
    public void setFkFoodId(String fkFoodId) {
        this.fkFoodId = fkFoodId == null ? null : fkFoodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_foodclass.fk_foodclass_id
     *
     * @return the value of food_foodclass.fk_foodclass_id
     *
     * @mbg.generated
     */
    public String getFkFoodclassId() {
        return fkFoodclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_foodclass.fk_foodclass_id
     *
     * @param fkFoodclassId the value for food_foodclass.fk_foodclass_id
     *
     * @mbg.generated
     */
    public void setFkFoodclassId(String fkFoodclassId) {
        this.fkFoodclassId = fkFoodclassId == null ? null : fkFoodclassId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_foodclass
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fkFoodId=").append(fkFoodId);
        sb.append(", fkFoodclassId=").append(fkFoodclassId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}